// Code generated by Kaiju Engine Editor; DO NOT EDIT.

package main

import (	_ "kaiju/engine_entity_data/engine_entity_data_audio"
	_ "kaiju/engine_entity_data/engine_entity_data_camera"
	_ "kaiju/engine_entity_data/engine_entity_data_light"
	_ "kaiju/engine_entity_data/engine_entity_data_particles"
	_ "kaiju/engine_entity_data/engine_entity_data_physics"
	_ "kaiju/engine_entity_data/engine_entity_data_skin_animation"
	_ "kaiju/engine_entity_data/engine_entity_data_tween_transform"
	_ "game/game_setup"
	_ "game/main_menu"
)